openapi: '3.0.2'
info:
  title: Aula 14
  version: '1.0'
  description: API de documentação da aula 14
  contact:
    name: Erick Medeiros
servers:
  - url: http://localhost:3000/
    description: Servidor de teste
paths:             
  /users:
    get:
      operationId: getUsuarios
      summary: Obtém todos os usuários do sistema
      tags:
        - Usuários
      responses:
        '200':
          description: Lista de usuários
          content:
            appication/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref:  "#/components/schemas/Usuario"
    post:
      summary: Create usuário.
      tags:
        - Usuários
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string  
      responses: 
        '200':
          description: Created    
components:
  schemas:
    Usuario:
      type: object
      properties:
        name:
          type: string
          description: Nome do usuário
          example: Erick Medeiros
        email:
          type: string
          description: E-mail do usuário
          example: foo@bar.com.br
        password:
          type: string
          description: Password do usuário
          example: senha123
    Erro:
      type: object
      properties:
        msg:
          type: string
          description: Mensagem de erro
          example: Usuário não encontrado!
